language: python
python:
    - "2.7"
install: "pip  install -r requirements.txt"
before_script:
    - autopep8 -ir *
    - flake8 --max-complexity=6 --exclude=*.txt,*.md --max-line-length=200 *
script:
    - lettuce AceptanceTest
    - cd UnitTest
    - python testCalculator.py
    - coverage run --branch testCalculator.py
    - coverage report -m
